apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
  labels:
    app: jenkins-set
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jenkins-set
  template:
    metadata:
      labels:
        app: jenkins-set
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: 2
          requests:
            memory: "250Mi"
            cpu: 1
        ports:
        - containerPort: 8080
