apiVersion: v1
kind: Service
metadata:
  name: jenkins-extip
spec:
  selector:
    my-pod: my-jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8080
  externalIPs:
    - 10.0.0.95
