apiVersion: v1
kind: LimitRange
metadata:
  name: jenkins-limitrange
  namespace: jenkins
spec:
  limits:
    - default: 
        cpu: 1
        memory: 500Mi
      defaultRequest: 
        cpu: 1
        memory: 500Mi
      type: Container
