apiVersion: v1
kind: ResourceQuota
metadata:
  name: jenkins-resoucequota
  namespace: jenkins
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
