apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-secrets-reader
  namespace: dev
subjects:
- kind: ServiceAccount
  name: secrets-reader
  namespace: dev
roleRef:
  kind: Role
  name: read-secrets
  apiGroup: rbac.authorization.k8s.io
